### ISSUE TITLE
oda-controller-ingress: seccon container memory and cpu leak, no logs

### ISSUE THREAD

**Issue by ycardon-pro** [tmforum-oda/oda-ca#50]
Hi,

I'm deploying the master branch of https://github.com/tmforum-oda/oda-canvas-charts (merged 11 days ago with the v1alpha3) on a Rancher RKE cluster.

When the `seccon` container of the `oda-controller-ingress` pod is starting, it takes 100% of 1 CPU and memory consumption linearly grows (around 1Gb / 10mn).

I do not get any logs, so it's hard to tell what's happening or what is misconfigured.

Help on this issue / ideas to debug would be really welcomed as it prevent us from deploying the canvas.

Note that a similar issue is mentioned on [slack](https://tmforumodacom-aqv6069.slack.com/archives/C01CGGDDLCQ/p1626433083056900)

Yann.

**Comment by brian-burton** [comment]
Hi @ycardon-pro, thanks for raising the issue.

My initial investigation seem to implicate the flask development server as the culprit, so I'm testing a new version of the security listener with [Waitress](https://docs.pylonsproject.org/projects/waitress/en/stable/) as the WSGI server instead of the flask development server.

I'm hoping to get a bugfix PR done in the next working day or so, but I need to verify that I don't break anything else first.
